# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options


deploy1:
  stage: deploy
  script:
    - git remote -v
