#!/bin/sh

echo Downloading scripts and config files...
curl -o jab.sh run.eloraju.xyz/jab/jab 1>/dev/null 2>&1
curl -o jab.conf run.eloraju.xyz/jab/conf 1>/dev/null 2>&1
curl -o jab.pkgs run.eloraju.xyz/jab/pkgs 1>/dev/null 2>&1
echo Downloaded:
echo -e "* jab.sh\t- This is the script you will eventually run. You should check this out to see what it does.\n"
echo -e "* jab.conf\t- Config file that exports all the variables used with the installation script. Change this to suit your needs\n"
echo -e "* jab.pkgs\t- All the packages that are going to get installed along the base system. You can add or remove stuff from here as much as you like. It's your system :) \n"

echo Tweak the jab.conf file to suit your needs
echo Then run sh jab ./config to start the fun