#!/bin/sh

echo -e "\nDownloading scripts and config files...\n"
curl -o jab.sh run.eloraju.xyz/jab/jab 1>/dev/null 2>&1
curl -o jab.conf run.eloraju.xyz/jab/conf 1>/dev/null 2>&1
curl -o jab.pkgs run.eloraju.xyz/jab/pkgs 1>/dev/null 2>&1
curl -o jab-chroot.sh run.eloraju.xyz/jab/chroot 1>/dev/null 2>&1
cat << EOF
Downloaded:
    * jab.sh            - This is the script you will eventually run. You should
                          check this out to see what it does.

    * jab-chroot.sh     - This script is run inside the newly installed system to
                          set it up to be ready to use. Check it out

    * jab.conf          - Config file that exports all the variables used with the
                          installation script. Change this to suit your needs

    * jab.pkgs          - All the packages that are going to get installed along
                          the base system. You can add or remove stuff from here
                          as much as you like. It's your system :)

Tweak the jab.conf file to suit your needs
Then run "sh jab.sh"
See you on the other side o/
EOF
