#!/bin/sh
### JAB - Juusos Arch Bootstrapper
### Order of operations
# 1. Enable multilib
# 1. Run pacman -S
# 2. Generate user 
# 3. Do some config stuff
# 4. Pull config files down
# 5. Install yay and yay packages
# 6. Pull wallpapers & scripts
# 7. Pull work stuff

USERNAME=$1

# Enables multilib (for steam 'n stuff)
enablePacmanMultilib() {
   sed -i "/\[multilib\]/, /Include/"'s/^#//' /etc/pacman.conf
   # And add some bling to pacman :)
   sed '/#Verbose/a ILoveCandy\nColor' pacman.conf
}


# Create a new user. This is the only param provided for the whole program 🤷
#generateUser() {
#    useradd -m -G wheel docker $1
#    UHOME=/home/$1
#}

# Generates ssh-keys for my work and personal repos
generateSSHKeys() {
    [ -d $HOME/.ssh ] || mkdir $HOME/.ssh
    cp ./templates/ssh.config $HOME/.ssh/config
    ssh-keygen
}

# Throw in the keyboard config
copyKeyboardConfig() {
    cp templates/00-keyboard.conf /etc/X11/xorg.conf.d/00-keyboard.conf
}

# Enable and start all kinds of services
enableServices() {
    systemctl enable --now docker systemd-networkd systemd-resolved
}

# Pull stuff

# Install yay and yay packages
installYayAndPackages() {
    cd /tmp
    git clone https://aur.archlinux.org/yay.git
    cd yay
    sudo -u juuso makepkg -si
    # Check that yay is working
    (yay -Q >> /dev/null && yay -S $(grep -vE '^#|^$'./yay-pkgs)) || error "yay didn't install correctly"
}

enablePacmanMultilib
installYayAndPackages
generateSSHKeys
copyKeyboardConfig
enableServices




